---
variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

default:
  image: ghcr.io/astral-sh/uv:0.5-python3.12-alpine
  cache:
    paths:
      - .cache/uv
  before_script:
    - apk add git
    - python --version; uv --version  # For debugging

pytest:
  stage: test
  image: ghcr.io/astral-sh/uv:0.5-python$PY_VERSION-alpine
  script:
    - uv sync --extra test
    - uv run pytest --cov=moodle_tools --cov-report term-missing:skip-covered --junitxml=pytest.xml tests
  artifacts:
    when: always
    paths:
      - pytest.xml
    reports:
      junit: pytest.xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  rules:
    # Run for all changes to a merge request's source branch
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run for all changes to the default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  parallel:
    matrix:
      - PY_VERSION: ["3.11", "3.12", "3.13"]

docs:
  stage: deploy
  script:
    - uv sync --extra docs
    - mv docs/assets public
    - uv run pdoc
      -o "public"
      --docformat google
      --favicon "/moodle-tools/favicon.ico"
      --footer-text "Moodle Tools, © 2024 DIMA."
      --logo "/moodle-tools/dima_logo.svg"
      --logo-link https://tu.berlin/dima
      ./src/moodle_tools
  pages: true
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger a documentation build
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
