---
default:
  image: python:3.11
  cache:
    paths:
      - .cache/pip
  before_script:
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install ".[dev]"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

pytest:
  stage: test
  script:
    # Run tests with coverage
    - pytest --cov=moodle_tools --cov-report term-missing:skip-covered --junitxml=pytest.xml tests
  artifacts:
    when: always
    paths:
      - pytest.xml
    reports:
      junit: pytest.xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  rules:
    # Run for all changes to a merge request's source branch
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run for all changes to the default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - mv docs/assets public
    - pdoc
      -o "public"
      --docformat google
      --favicon "/isda/isda-streaming/favicon.ico"
      --footer-text "Moodle Tools, © 2024 DIMA."
      --logo "/isda/isda-streaming/dima_logo.svg"
      --logo-link https://tu.berlin/dima
      ./src/moodle_tools
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger a pages deploy
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
