---
default:
  image: python:3.11
  before_script:
    - pip install ".[dev]"

pytest:
  stage: test
  script:
    # Run tests with coverage
    - pytest --cov=moodle_tools --cov-report=html tests
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    paths:
      # Store coverage reports as artifacts
      - htmlcov/
  rules:
    # Run for all changes to a merge request's source branch
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run for all changes to the default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - mv docs/assets public
    - pdoc -o "public" --docformat google --favicon "favicon.ico" --footer-text
      "Moodle Tools, © 2024 DIMA." --logo "dima_logo.svg" --logo-link
      https://tu.berlin/dima ./src/moodle_tools
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
