# .gitlab-ci.yml

stages:
  - test

pytest:
  stage: test
  image: python:3.11
  before_script:
    - pip install pytest pytest-cov
  script:
    - pip install .
    - pytest --cov=moodle_tools --cov-report=html tests  # Run tests with coverage
  artifacts:
    paths:
      - htmlcov/  # Store coverage reports as artifacts
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  # Run for all changes to a merge request's source branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH       # Run for all changes to the default branch
